- name: configure catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable module nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /opt/app
      

  - name: create app direcotry
    ansible.builtin.file:
      path: /opt/app
      state: directory
      mode: 0755 

  - name: download the code file from web
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip   
      dest: /tmp/catalogue.zip

  - name: unzip or extract the catalogue code
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /opt/app
      remote_src: yes
  
  - name: install Nodejs dependencies
    community.general.npm:
      path: /opt/app
  
  - name: copy the catalogue service to systemd directory 
    ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

  - name: daemon reload
    ansible.builtin.systemd_service:
    daemon_reload: true

  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes



